// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7CrcykJnI9NmxESudnHA-p04Yk_quTzg',
    appId: '1:344915601574:web:6ff842c02c3006c580ac67',
    messagingSenderId: '344915601574',
    projectId: 'gabriel-b-diario-de-viagens',
    authDomain: 'gabriel-b-diario-de-viagens.firebaseapp.com',
    storageBucket: 'gabriel-b-diario-de-viagens.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHhO_NwkeVcEz-26ut6zJG_X3cM32BE_U',
    appId: '1:344915601574:android:eaec02e42c46555080ac67',
    messagingSenderId: '344915601574',
    projectId: 'gabriel-b-diario-de-viagens',
    storageBucket: 'gabriel-b-diario-de-viagens.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk5UfDJRriP9Hp4Hmc0iW_LpYxfcNRNGg',
    appId: '1:344915601574:ios:7ae98861b66c981b80ac67',
    messagingSenderId: '344915601574',
    projectId: 'gabriel-b-diario-de-viagens',
    storageBucket: 'gabriel-b-diario-de-viagens.appspot.com',
    iosBundleId: 'io.github.ninjabitroom.diarioDeViagens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk5UfDJRriP9Hp4Hmc0iW_LpYxfcNRNGg',
    appId: '1:344915601574:ios:7ae98861b66c981b80ac67',
    messagingSenderId: '344915601574',
    projectId: 'gabriel-b-diario-de-viagens',
    storageBucket: 'gabriel-b-diario-de-viagens.appspot.com',
    iosBundleId: 'io.github.ninjabitroom.diarioDeViagens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7CrcykJnI9NmxESudnHA-p04Yk_quTzg',
    appId: '1:344915601574:web:351099bde978c80580ac67',
    messagingSenderId: '344915601574',
    projectId: 'gabriel-b-diario-de-viagens',
    authDomain: 'gabriel-b-diario-de-viagens.firebaseapp.com',
    storageBucket: 'gabriel-b-diario-de-viagens.appspot.com',
  );

}